### ISSUE TITLE
Rollover API misalignment

### ISSUE THREAD

**Issue by jgprogramming** [opendistro-for-elasticsearch/index-management#101]
## Expected Behavior
When providing ILM with policy configured with standard [Elastic rollover API  ](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-rollover-index.html) variables I expect it to parse them properly such as:
```
"actions": [
    {
        "rollover": {
            "max_docs": 1000,
            "max_age": "1h",
            "max_size": "40gb"
        }
    }
]
```

## Current Behavior
Opendistro ILM expects different variables, such as `min_size`,`min_index_age` and `min_doc_count`. Not only are they inconsistent in ILM (`min_size` instead of `min_index_size`) they are misaligned with elastic API (min vs max)

## Possible Solution
Align current Opendistro ILM variables with elastic ones.

## Context
This issue arose during transferring our ILM policies from elastic to opendistro. Translating those variables to opendistro standard would force us to provide further documentation on rolling APi instead of pointing to official docs.

**Comment by dac388** [comment]
how is this still an issue?

**Comment by dbbaughe** [comment]
Hi @jgprogramming @dac388,

This is unlikely to change. We need these options to be more explicit in ISM because these are not options just passed through to the rollover API. They are calculated and checked before calling rollover. We did this so we can add more conditions people might want instead of only relying on rollover API.

e.g. we have plans to not only have "min_index_age", but also "min_state_age" and other conditions.
As for the min vs max, that was a design decision we went with and is also unlikely to change at this time.
