### ISSUE TITLE
Update Policy Schedule Interval

### ISSUE THREAD

**Issue by jackmead515** [opendistro-for-elasticsearch/index-management#229]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to modify the .opendistro-ism-config schedule interval for a policy attached to an index. It's default is at 30 minutes and that is simply too long to wait when testing and debugging. As far as I understand it, the policy actions/transitions will be checked on this interval.

**Describe the solution you'd like**
Using the node elastic search client:
```
await es.client.update({
        id: 'my-doc-id',
        index: '.opendistro-ism-config',
        body: {
            doc: {
                managed_index: {
                    schedule: {
                        interval: {
                            period: 10,
                            unit: 'Seconds',
                        },
                    },
                },
            },
        },
    });
```
I should be able to update it. And I can, I'd just like for it to take affect. I don't know if it does or does not.

**Additional context**
I'm running an AWS ES cluster running v7.4

**Comment by dbbaughe** [comment]
Hey @jackmead515,

Technically yes, you can upgrade the documents directly on AmazonES, although you will be bypassing our current recommendations for the default intervals. This was because there were performance improvements for cluster state updates that are out in ODFE now, but are still deploying for AmazonES.

If you update the document directly.. what should theoretically happen is the Job Scheduler plugin should de-schedule and re-schedule the job as it's been updated. The newly scheduled job should run at the new interval.

In your example though you have 10 seconds which we don't allow. The minimum interval that can be scheduled is 1 minute. I'm guessing by modifying the document, every time ISM/Job Scheduler tries to parse the document it's failing because it does not have "Seconds" as a unit in the Interval parser.

**Comment by jackmead515** [comment]
@dbbaughe Thanks for getting back so quickly. Do you think that could be a reason for my managed index being stuck with a status of "Initializing"? I'll update and see if anything happens.

**Comment by dbbaughe** [comment]
@jackmead515 

Well it's not something we want to publicize/allow really. Ideally no one should be touching those documents at all besides the plugin itself. So not sure we'll document how to modify the internal document.

The reason yours is getting reset is because we have this logic at the end of a run for updating the job interval. So it's reading the job_interval cluster setting and seeing it's 30 minutes and your job is 1 minute and updating it. On the service we don't expose the job_interval setting because of previously mentioned performance considerations.

```
if (managedIndexConfig.hasDifferentJobInterval(jobInterval)) {
    updateJobInterval(managedIndexConfig, jobInterval)
}
```

So if you want to continue testing at a high frequency, unfortunately you would need to just make a repeatable interval update request and call it after each job execution.

i.e. apply policy to index -> job is created to run at 30 minutes -> change to 1 minute -> job runs, but is reset to 30 minutes -> change to 1 minute -> job runs, but is reset to 30 minutes -> etc.

Definitely not great, because of our restriction on the job_interval it seems we overlooked customers trying to test it out on the service. We'll be slowly easing the frequency of the jobs over time on the service which should help, but I don't think we'd be allowing a 1 minute frequency at time soon. Your best best for now is the above updates.

**Comment by jackmead515** [comment]
With all respect and to be frank, the performance issue sounds like my problem. I should be able to make that decision for myself. Unless I'm misunderstanding what you mean by that. In addition, I'd think that being able to set it to 1 hour, 2 hours, etc. would improve the performance for those of us that are extremely nit picky.

But hey! You said it yourself, not something the team is considering. Thank you for your help @dbbaughe. Maloha.

**Comment by dbbaughe** [comment]
@jackmead515 

For reference, users on ODFE do have access to the job_interval setting to make their own choice:
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/settings/

It's not configurable on the Amazon Elasticsearch Service as of now. The reason we have the limit on the service is because of our own load testing and to prevent anyone from shooting themselves in the foot if they are under the assumption they can apply a policy to 10,000 indices and have it run every 1 minute. It's unfortunately not solely your problem as it is a co-managed service and we do get paged when things go wrong, so we came up with 30 minutes as our currently acceptable interval when taking that into account. If it's not executing fast enough for you, please feel free to make a request through the AWS channels and it can help us prioritize. This wasn't a one-way door decision that will never change, but rather a decision for the initial release. As we make improvements those restrictions will naturally lift.

**Comment by jackmead515** [comment]
Looks like the bottom of this AWS DOC shows reference to the ISM settings that you can change:
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ism.html

I'll leave it for reference too.
